# Change these first
owner: DamienCegos # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Cegos FR
    url: https://www.cegos.fr
  - name: Cegos COM
    url: https://www.cegos.com/en
  - name: ib Cegos
    url: https://www.ib-formation.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Cegos
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Welcome to the Status Page of Cegos Websites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/DamienCegos/upptime
    - title: Cegos
      href: https://www.cegos.fr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
